name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # change this if your main branch has a different name

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: npm install -g firebase-tools

      - run: npm ci
        if: hashFiles('package-lock.json') != ''

      - run: npm run build --if-present

      - run: firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }}
